name: wallet_connect_flutter_v2
description: Wallet Connect v2 client made in flutter.
version: 0.1.0
homepage: https://github.com/Eucalyptus-Labs/wallet-connect-flutter-v2

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hex: ^0.2.0
  web_socket_channel: ^2.2.0
  http: ^0.13.5
  cryptography: ^2.0.5
  convert: ^3.0.1
  json_annotation: ^4.7.0
  pointycastle: ^3.6.2
  x25519: ^0.1.1
  bs58: ^1.0.2
  ed25519_edwards: ^0.3.1
  json_rpc_2: ^3.0.2
  event: ^2.1.2
  stream_channel: ^2.1.0
  shared_preferences: ^2.0.17
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk:
      flutter
  build_runner: ^2.0.0
  json_serializable: ^6.5.3
  dependency_validator: ^3.2.2
  mockito: ^5.3.2

