name: walletconnect_flutter_v2
description: This repository contains oficial implementation of WalletConnect v2 protocols for Flutter applications. The communications protocol for web3.
version: 2.2.1
repository: https://github.com/WalletConnect/WalletConnectFlutterV2

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  bs58: ^1.0.2
  convert: ^3.0.1
  cryptography: ^2.0.5
  ed25519_edwards: ^0.3.1
  event: ^2.1.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  http: ^1.2.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  package_info_plus: ^5.0.1
  pointycastle: ^3.7.4
  shared_preferences: ^2.2.2
  stack_trace: ^1.10.0
  stream_channel: ^2.1.0
  universal_io: ^2.2.2
  web3dart: ^2.7.2
  web_socket_channel: ^2.4.0
  x25519: ^0.1.1

dev_dependencies:
  build_runner: ^2.4.7
  build_version: ^2.1.1
  dependency_validator: ^3.2.2
  eth_sig_util: ^0.0.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk:
      flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.0
  mockito: ^5.4.3

