name: walletconnect_flutter_v2_wallet
description: An example wallet for WalletConnect v2 built with Flutter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  fl_toast: ^3.1.0
  qr_bar_code_scanner_dialog:
    path: packages/qr-bar-code-scanner-dialog
  get_it: ^7.2.0
  eth_sig_util: ^0.0.9
  get_it_mixin: ^4.0.0
  package_info_plus: ^7.0.0
  convert: ^3.0.1
  url_launcher: ^6.2.2
  kadena_dart_sdk: ^2.3.2
  solana: ^0.30.4
  polkadart_keyring: ^0.4.3
  polkadart: ^0.4.3
  walletconnect_flutter_v2:
    path: ../..

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.5.3
  dependency_validator: ^3.2.2

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
