name: walletconnect_flutter_v2_dapp
description: An example dApp for WalletConnect v2 built with Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  qr_flutter: ^4.0.0
  json_annotation: ^4.8.1
  fl_toast: ^3.1.0
  url_launcher: ^6.2.2
  # intl: ^0.19.0
  package_info_plus: ^7.0.0
  walletconnect_modal_flutter: ^2.1.19
  # walletconnect_flutter_v2:
  #   path: ../..

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.5.3
  dependency_validator: ^3.2.2

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
