name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    name: Publish to pub.dev
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
    # Checkout the repo
    - uses: actions/checkout@v3

    # Install Flutter
    - name: Install and set Flutter version
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    # Setup Dart SDK
    - uses: dart-lang/setup-dart@v1

    # Setup Dependencies
    - uses: ./.github/actions/dependencies

    # Publish
    - name: Check Publish Warnings
      shell: bash
      run: flutter pub publish --dry-run
    - name: Publish Package
      shell: bash
      run: flutter pub publish -f