name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    name: Publish to pub.dev
    permissions:
      id-token: write
    runs-on: macos-latest-xlarge
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
      
      # Install Flutter and Dependencies
      - uses: ./.github/actions/dependencies

      # Setup Dart SDK
      - uses: dart-lang/setup-dart@v1

      # Publish
      - name: Check Publish Warnings
        shell: bash
        run: flutter pub publish --dry-run

      - name: Publish Package
        shell: bash
        run: flutter pub publish -f
      
      # Notify
      - name: Notify Channel
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: 'INCOMING_WEBHOOK'
        with:
          payload: |-
            {
              "text":"ðŸš€ WalletConnectFlutterV2 *${{ github.ref_name }}* was just published at https://pub.dev/packages/walletconnect_flutter_v2"
            }

# Launch locally
# act -j publish --container-architecture linux/amd64 -P macos-latest-xlarge=-self-hosted --secret-file .github/workflows/.env.secret -W .github/workflows/publish.yml